//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controladores.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controladores.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_cuadratico {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_cuadratico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_derivativo {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_derivativo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_derivativo_cuadratico {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_derivativo_cuadratico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_derivativo_escalon {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_derivativo_escalon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_derivativo_rampa {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_derivativo_rampa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_escalon {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_escalon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral_cuadratico {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral_cuadratico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral_derivativo {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral_derivativo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral_derivativo_cuadratico {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral_derivativo_cuadratico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral_derivativo_escalon {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral_derivativo_escalon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral_derivativo_rampa {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral_derivativo_rampa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral_escalon {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral_escalon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_integral_rampa {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_integral_rampa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlador_proporcional_rampa {
            get {
                object obj = ResourceManager.GetObject("controlador_proporcional_rampa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ecuaciones {
            get {
                object obj = ResourceManager.GetObject("ecuaciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_cuadratico {
            get {
                object obj = ResourceManager.GetObject("error_cuadratico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_escalon {
            get {
                object obj = ResourceManager.GetObject("error_escalon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_rampa {
            get {
                object obj = ResourceManager.GetObject("error_rampa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
