//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeoriaDeControl.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeoriaDeControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Blanco {
            get {
                object obj = ResourceManager.GetObject("Blanco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Formula_estándar {
            get {
                object obj = ResourceManager.GetObject("Formula estándar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaEscalon1Orden {
            get {
                object obj = ResourceManager.GetObject("FormulaEscalon1Orden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaEscalon2Orden1 {
            get {
                object obj = ResourceManager.GetObject("FormulaEscalon2Orden1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaEscalon2Orden2 {
            get {
                object obj = ResourceManager.GetObject("FormulaEscalon2Orden2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaEscalon2Orden3 {
            get {
                object obj = ResourceManager.GetObject("FormulaEscalon2Orden3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaImpulso1Orden {
            get {
                object obj = ResourceManager.GetObject("FormulaImpulso1Orden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaImpulso2Orden1 {
            get {
                object obj = ResourceManager.GetObject("FormulaImpulso2Orden1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaImpulso2Orden2 {
            get {
                object obj = ResourceManager.GetObject("FormulaImpulso2Orden2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaImpulso2Orden3 {
            get {
                object obj = ResourceManager.GetObject("FormulaImpulso2Orden3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaRampa1Orden {
            get {
                object obj = ResourceManager.GetObject("FormulaRampa1Orden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaRampa2Orden1 {
            get {
                object obj = ResourceManager.GetObject("FormulaRampa2Orden1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaRampa2Orden2 {
            get {
                object obj = ResourceManager.GetObject("FormulaRampa2Orden2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaRampa2Orden3 {
            get {
                object obj = ResourceManager.GetObject("FormulaRampa2Orden3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Formulas_asentamiento {
            get {
                object obj = ResourceManager.GetObject("Formulas asentamiento", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaSenoidal1Orden {
            get {
                object obj = ResourceManager.GetObject("FormulaSenoidal1Orden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaSenoidal2Orden1 {
            get {
                object obj = ResourceManager.GetObject("FormulaSenoidal2Orden1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaSenoidal2Orden2 {
            get {
                object obj = ResourceManager.GetObject("FormulaSenoidal2Orden2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaSenoidal2Orden3 {
            get {
                object obj = ResourceManager.GetObject("FormulaSenoidal2Orden3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormulaSenoidal2OrdenPhi {
            get {
                object obj = ResourceManager.GetObject("FormulaSenoidal2OrdenPhi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Funcion_overshoot {
            get {
                object obj = ResourceManager.GetObject("Funcion overshoot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Grafica_Overshoot_vs_Psi {
            get {
                object obj = ResourceManager.GetObject("Grafica Overshoot vs Psi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
